### ISSUE TITLE
Cant't install

### ISSUE THREAD

**Issue by rolfmblindgren** [Lisp-Stat/lisp-stat#2]
```
This is SBCL 2.1.3, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :lisp-stat)
To load "lisp-stat":
  Load 1 ASDF system:
    lisp-stat
; Loading "lisp-stat"
..
debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {70088A3863}>:
  SELECT:HEAD already names an ordinary function or a macro.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Replace the function binding
  1: [TRY-RECOMPILING              ] Recompile pprint and try loading it again
  2: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "data-frame" "pprint">.
  3: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "data-frame" "pprint">
                                     as having been successful.
  4:                                 Retry ASDF operation.
  5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  6:                                 Retry ASDF operation.
  7:                                 Retry ASDF operation after resetting the
                                     configuration.
  8: [ABORT                        ] Give up on "lisp-stat"
  9: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
 10:                                 Exit debugger, returning to top level.

(ENSURE-GENERIC-FUNCTION HEAD)
```

This is sbcl on m1 Mac, same issue with ccl on Intel Mac.

**Comment by Symbolics** [comment]
Lisp-Stat isn't yet in Quicklisp. I submitted an issue for it's inclusion (quicklisp/quicklisp-projects#2016). Normally quicklisp projects are updated once a month, so I expect it to be there at the end of April. The alternative is to do a manual install, described in the [installation](https://lisp-stat.dev/docs/getting-started/#installation) section of the docs.

**Comment by rolfmblindgren** [comment]
That's what I've done.

I'm at ”Try it out“, which is where the above occurs.

**Comment by Symbolics** [comment]
When did you do the checkout? I removed `head` and `tail` about a week ago after encountering this error. It could be that you pulled down the repositories before that change. Might want to pull from the `select` repository again.

Also, I pushed changes to `data-frame` yesterday and fixed a bug in `dfio` this morning that I'll push out now.

**Comment by rolfmblindgren** [comment]
I used the method described in the manual, have just run git pull everywhere, noticed some changes, but the issue stil stands.

**Comment by Symbolics** [comment]
What OS are you running? I'll try to reproduce with a fresh checkout in the morning. 

In the meantime, let's delete all your fasl files and start with a clean rebuild.

**Comment by vindarel** [comment]
What I tried myself:

I cloned lisp-stats' repository in QL's local-projects

    (asdf:clear-source-registry)

    quickload "lisp-stat" ->

> System "data-frame" not found
>   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

The main repository doesn't say to clone all other projects :] (https://github.com/Lisp-Stat/lisp-stat) I supposed it brings the dependencies itself, but maybe not yet.

(ql:dist-version "quicklisp")
"2020-12-20"

**Comment by Symbolics** [comment]
Ah, I think I see the problem. Thank you @vindarel for providing the clue.

The manual installation instructions left out the `select` repository, and that dependency was being pulled in from Quicklisp. Check out the Lisp-Stat version of select with:

```
git clone https://github.com/Lisp-Stat/select.git
```
and see if it builds properly.

**Comment by vindarel** [comment]
lisp-stat is now in the latest Quicklisp: http://blog.quicklisp.org/2021/04/april-2021-quicklisp-dist-update-now.html

to upgrade: (ql:update-dist "quicklisp")

**Comment by Symbolics** [comment]
@rolfmblindgren, are you still having problems installing?

**Comment by rolfmblindgren** [comment]
not as such, but still

? (in-package :ls-user)
#<Package "LS-USER">
? (load #P"LS:DATASETS;CAR-PRICES")
#P"/Users/roffe/quicklisp/dists/quicklisp/software/lisp-stat-20210411-git/datasets/car-prices.lisp"
? (mean 'car-prices)
> Error: There is no applicable method for the generic function:
>          #<STANDARD-GENERIC-FUNCTION CENTRAL-SAMPLE-MOMENTS #x302000E3B62F>
>        when called with arguments:
>          (CAR-PRICES :DEGREE 1 :WEIGHTS NIL)
> While executing: #<CCL::STANDARD-KERNEL-METHOD NO-APPLICABLE-METHOD (T)>, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Try calling it again
> Type :? for other options.

--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/

**Comment by rolfmblindgren** [comment]
OK, it works in GNU Emacs’ sly-mode.  But not when the same lisp executable is called from the shell.

--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/

**Comment by rolfmblindgren** [comment]
OK, ignore that … pass the variable unsuited, and this happens

? (mean car-prices)
2.810199998617172D0
? (median car-prices)
> Error: Undefined function :DOCUMENTATION called with arguments ("Returns median of SAMPLE.  SAMPLE must be a sequence of real numbers.") .
> While executing: #<STANDARD-METHOD MEDIAN (SEQUENCE)>, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry applying :DOCUMENTATION to ("Returns median of SAMPLE.  SAMPLE must be a sequence of real numbers.").
> Type :? for other options.
1 >

--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/

**Comment by Symbolics** [comment]
Fixed. You'll need to pull the latest change from numerical-utilities.

**Comment by Symbolics** [comment]
Still an issue?

**Comment by rolfmblindgren** [comment]
The issue seems to have been resolved. Thanks! :)

--
Rolf Lindgren
+47 455 19 940
http://www.grendel.no/
